

avatars = {
    1: "AgACAgIAAxkBAAIBsGiiu2RR4WSKFkhdfos_qLXl8lR9AAIB_TEbB4oZSYHPpg6Hgp4FAQADAgADeQADNgQ",
    2: "AgACAgIAAxkBAAIBsWiiu2QHxtzAN1CsFnBlUW-5EhC4AAIC_TEbB4oZSbvipZ0zAsNgAQADAgADeQADNgQ",
    3: "AgACAgIAAxkBAAIBsmiiu2SVhOeyIGzEPnOeeTnRDXCCAAID_TEbB4oZSREAAa0iVKWjhAEAAwIAA3kAAzYE",
    4: "AgACAgIAAxkBAAIBs2iiu2TZJ4LQelZF5Wlpq1bVaggKAAIE_TEbB4oZSfTP75btg-BLAQADAgADeQADNgQ",
    5: "AgACAgIAAxkBAAIBtGiiu2QWCdYqGriDpuPFEk3ODXLdAAIF_TEbB4oZSdIFRZDE54A9AQADAgADeQADNgQ",
    6: "AgACAgIAAxkBAAIBtWiiu2S5QUg7Yi-Nd_VV-2QCA_BRAAIG_TEbB4oZSXuWHZiNiqiTAQADAgADeQADNgQ"
}